TITLE PALINDROMO LEE HASTA 50 CHARS Y DICE SI ES ;PALINDROMO

.MODEL SMALL
.STACK 100H
.DATA
    MSG     DB 10,13,10,13,10,13,'DAME HASTA 50 CHARS:$'
    MSG_SI  DB 10,13, 'SI ES PALINDROMO$'
    MSG_NO  DB 10,13, 'NO ES PALINDROMO$'
    ST     DB 50 DUP('$'),'$'
    LEN     DW 0
    
.CODE
MAIN PROC 
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX,MSG
    MOV AH,9
    INT 21H
    MOV CX,50
    XOR SI,SI
    
 LEE_CHAR:
    MOV AH,1
    INT 21H
    CMP AL,13
    
    JE FIN
    MOV ST[SI], AL
    INC SI
   LOOP LEE_CHAR
   
FIN:

    ;SI TIENE CUANTOS CARACTERES LEI
    MOV LEN,SI
    MOV CX,LEN
DESPLEGA:
    MOV AH,2
    MOV DL,ST[SI]
    INT 21H
    DEC SI
    LOOP DESPLEGA
    
   LEA DX,ST
   MOV AH,9
   INT 21H
   MOV CX,LEN
   SHR CX,1
   MOV SI,LEN
   DEC SI
   XOR DI,DI
   
COMPARA:
MOV AL,ST[SI]
CMP AL,ST[DI]
JE SIGUE
JNE NO_ES

SIGUE:
    DEC SI
    INC DI
    LOOP COMPARA
SI_ES:
    LEA DX,MSG_SI
    JMP DISPLAY
NO_ES:
    LEA DX,MSG_NO
    
DISPLAY:
    MOV AH,9
    INT 21H
    
   MOV AH,4CH
   INT 21H
   
MAIN ENDP  
END MAIN
